### ISSUE TITLE
Break in init event

### ISSUE THREAD

**Issue by jcorbin** [Shougo/neosnippet.vim#394]
After updating this morning, I had the following break:
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/joshua/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 456, in on_event
[deoplete]     source.on_event(context)
[deoplete]   File "/Users/joshua/.config/nvim/plugged/neosnippet.vim/rplugin/python3/deoplete/sources/neosnippet.py", line 21, in on_event
[deoplete]     'values(neosnippet#helpers#get_completion_snippets())')
[deoplete]   File "/Users/joshua/Library/Python/3.6/lib/python/site-packages/neovim/api/nvim.py", line 226, in eval
[deoplete]     return self.request('nvim_eval', string, **kwargs)
[deoplete]   File "/Users/joshua/Library/Python/3.6/lib/python/site-packages/neovim/api/nvim.py", line 131, in request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/Users/joshua/Library/Python/3.6/lib/python/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):E117: Unknown function: js_encode'
[deoplete] Exception during neosnippet.on_event for event 'Init': b'Vim(return):E117: Unknown function: js_encode'.  Use :messages for error details.
```

Which I was able to fix with this hack:

```
diff --git a/autoload/neosnippet/helpers.vim b/autoload/neosnippet/helpers.vim
index 8053d0a..e391a55 100644
--- a/autoload/neosnippet/helpers.vim
+++ b/autoload/neosnippet/helpers.vim
@@ -158,10 +158,10 @@ function! neosnippet#helpers#substitute_selected_text(type, text) abort "{{{
 endfunction"}}}
 
 function! neosnippet#helpers#vim2json(expr) abort "{{{
-  return has('patch-7.4.1498') ? js_encode(a:expr) : string(a:expr)
+  return has('patch-7.4.1498') ? json_encode(a:expr) : string(a:expr)
 endfunction "}}}
 function! neosnippet#helpers#json2vim(expr) abort "{{{
-  sandbox return has('patch-7.4.1498') ? js_decode(a:expr) : eval(a:expr)
+  sandbox return has('patch-7.4.1498') ? json_decode(a:expr) : eval(a:expr)
 endfunction "}}}
 
 function! s:is_beginning_of_line(cur_text) abort "{{{
```

Not sure what the right way to fix is (probably some other layer feature detection? not sure...)

**Comment by Shougo** [comment]
Fixed in the latest version.
