### ISSUE TITLE
List all available snippets with Denite fails

### ISSUE THREAD

**Issue by schoettl** [Shougo/neosnippet.vim#434]
`:Denite neosnippet` brings this error:

```
[denite] Traceback (most recent call last):
[denite]   File "<string>", line 9, in _temporary_scope
[denite]   File "/home/jakob/.cache/dein/.cache/.vimrc/.dein/rplugin/python3/denite/ui/default.py", line 
71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/jakob/.cache/dein/.cache/.vimrc/.dein/rplugin/python3/denite/ui/default.py", line 
119, in _start
[denite]     self.init_denite()
[denite]   File "/home/jakob/.cache/dein/.cache/.vimrc/.dein/rplugin/python3/denite/ui/default.py", line 
660, in init_denite
[denite]     self._denite.on_init(self._context)
[denite]   File "/home/jakob/.cache/dein/.cache/.vimrc/.dein/rplugin/python3/denite/denite.py", line 172,
 in on_init
[denite]     raise NameError('Source "' + name + '" is not found.')
[denite] NameError: Source "neosnippet" is not found.
[denite] Please execute :messages command.
```

Whats wrong?

**Comment by Shougo** [comment]
`Denite unite:neosnippet`

neosnippet source is only available in unite.vim.

**Comment by schoettl** [comment]
Wouldn't it make sense to implement a source for Denite? In my understanding, Unite is discontinued and Denite is the future..

**Comment by Shougo** [comment]
I don't want to implement it.
neosnippet uses insert mode feature in unite.vim to implement expand feature.
It is not supported in denite.

Just listing is OK.  though.

**Comment by Shougo** [comment]
I have implemented just listing source.

**Comment by schoettl** [comment]
Ok, thank you. Hmm, without expand feature I will probably use Unite, though.
