### ISSUE TITLE
E739 Cannot create directory

### ISSUE THREAD

**Issue by rmolin88** [Shougo/neosnippet.vim#435]
OS: Windows 7
Neovim: 0.3.0

```python
[deoplete] Traceback (most recent call last):
  File "C:/Users/User/AppData/Local/vim-data/vim_plugins/deoplete.nvim/rplugin/python3\deoplete\child.py", line 499, in _on_event
    source.on_event(context)
  File "C:\Users\User\AppData\Local\vim-data\vim_plugins\neosnippet\rplugin/python3/deoplete\sources\neosnippet.py", line 21, in on_event
    'values(neosnippet#helpers#get_completion_snippets())')
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\neovim\api\nvim.py", line 250, in eval
    return self.request('nvim_eval', string, **kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\neovim\api\nvim.py", line 140, in request
    res = self._session.request(name, *args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\neovim\msgpack_rpc\session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim(call):E739: Cannot create directory C:/Users/User/AppData/Local/Temp\\neosnippets: file already exists'
Exception during neosnippet.on_event for event 'Init': b'Vim(call):E739: Cannot create directory C:/Users/User/AppData/Local/Temp\\neosnippets: file already exists'.  Use :messages / see above for error details.
```

**Comment by Shougo** [comment]
Please remove `C:/Users/User/AppData/Local/Temp\\neosnippets` file.

**Comment by rmolin88** [comment]
I think deleting the folder if its there already should be addressed in the code. It happens every few days.

Thanks,

**Comment by Shougo** [comment]
Sorry, I don't want to implement the feature.
